### PR TITLE
website interface and icons added

### PR DESCRIPTION
**Pull request by spabolu**
hello there, 
i'm new to pull requesting and found this repo on unraid. 
i made some changes to the website itself and added new icons and added metadata tags. 

one improvement we can add is default to the `website.png` file when the text doesn't belong to other social media icons. right now, it shows nothing but having the custom website icon makes it look good.

### CODE REVIEW

**Comment by diamkil** [comment]
I'll be taking a look tonight after work. Only thing that might need change is that it's not recommended to mix Yarn and NPM so for contributing I'd say to use only yarn

**Comment by spabolu** [comment]
i was not aware of that. thanks for letting me know.
i'll make the `README.md` show only `yarn`. also what did you think of defaulting to the custom website picture if the website doesn't detect a social media?

**Comment by diamkil** [comment]
I didn't have the chance to try it yet. Just read a bit through the code

**Comment by spabolu** [comment]
understood.

**Comment by diamkil** [comment]
What do you think about that?

**Review by spabolu — COMMENTED** [review]
hey i added the margin because i wanted the white square around the website. i kinda liked the white square around the page, but it may be a personal preference. you can decide on whether we should keep it or not.

**Review by spabolu — COMMENTED** [review]
the centered social networks is a style preference that i liked after looking at tappy.tech and linktr.ee i personally liked it, but you can decide on what to do with the centered social networks.

**Comment by diamkil** [comment]
I personnally feels it looks weird to have a white border but the website background is black. If you have a color for the sides and want to code that one back in I'll be happy to include it (also note you didn't put px or rem or vx when you set the margin so it didn't apply, simply aplying the default margin)

**Comment by diamkil** [comment]
> the centered social networks is a style preference that i liked after looking at tappy.tech and linktr.ee i personally liked it, but you can decide on what to do with the centered social networks.

If we have some way to be showing them as to not be a list. Centered would be very good

**Comment by diamkil** [comment]
I do have to say the code you did for the part with the name and the image is very good. It looks nice and adapts to screen size

**Comment by spabolu** [comment]
> I personnally feels it looks weird to have a white border but the website background is black. If you have a color for the sides and want to code that one back in I'll be happy to include it (also note you didn't put px or rem or vx when you set the margin so it didn't apply, simply aplying the default margin)

understood. we can remove it.

**Comment by diamkil** [comment]
I think I'll be merging as it is right now. If you still want to make more edits I'd love to get Pull Requests and work more on the app

**Comment by spabolu** [comment]
> If we have some way to be showing them as to not be a list. Centered would be very good

Ok. let's put the profile image and name centered while leaving these justified to the left like before.

**Comment by diamkil** [comment]
Also is there a benifice to using the latest version of nodejs instead of the recommended lts?

**Comment by spabolu** [comment]
> Also is there a benifice to using the latest version of nodejs instead of the recommended lts?

not that i know of. i just like taking risks and having the latest version so i used it instead.

also, how does the docker container get created? is it automatic or do you build it and upload the image?

**Comment by spabolu** [comment]
another thing is maybe we should add a screenshot of how the webpage looks like in the `README.md` and add some tags and basic info in the About section in the side of the repo.

**Comment by diamkil** [comment]
I use my Docker-Build.sh script. It creates a tag with the commit number and the latest one then pushes to hub.
Just ran it

**Comment by diamkil** [comment]
> another thing is maybe we should add a screenshot of how the webpage looks like in the `README.md` and add some tags and basic info in the About section in the side of the repo.

Defenitly good idea. I'll be working on that tomorrow

**Comment by diamkil** [comment]
@spabolu may I ask where the images are from so I can get them from the same place if I decide to add some socials?

**Comment by spabolu** [comment]
found them from different sources. most of them came from [here](https://www.iconfinder.com/social-media-icons). I edited and made the icons using PhotoShop for the rest.

**Pull request merged**
